name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        run_cfg: [ { cmake_args: "-DUSE_SANITIZERS=ON", test_args: "" }, {cmake_args: "", test_args: "-T memcheck"} ]
    defaults:
      run:
        working-directory: ${{github.workspace}}/build
    steps:
    - uses: actions/checkout@v2
    - run: mkdir build
      working-directory: ${{github.workspace}}
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y valgrind
    - name: CMake
      run: cmake ${{github.workspace}} ${{matrix.run_cfg.cmake_args}}
    - name: Build
      run: make
    - name: Test
      run: ctest ${{matrix.run_cfg.test_args}}
